import { z } from "zod";
import { generateObject } from "ai";
import { getLanguageModel } from "@/lib/ai/openrouter";

export interface ArtifactRef {
  kind: "file" | "image" | "chart" | "code_output";
  displayName: string;
  sandboxPath: string | null;
  url: string | null;
  description: string;
  sourceToolName: string;
}

export interface NodeHandoff {
  agentName: string;
  role: string;
  outcomeSummary: string;
  reasoningSummary: string;
  artifacts: ArtifactRef[];
  workspaceHint: string;
}

interface ToolCallDetail {
  toolName: string;
  args: Record<string, unknown>;
  result: unknown;
}

export const NodeHandoffSchema = z.object({
  outcomeSummary: z
    .string()
    .describe(
      "2-3 sentence summary of what this agent accomplished. Be specific about deliverables."
    ),
  reasoningSummary: z
    .string()
    .describe("Brief explanation of key decisions made and approach taken."),
});

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null;
}

function getString(value: unknown): string | null {
  return typeof value === "string" && value.trim().length > 0 ? value : null;
}

function extractFromToolCall(detail: ToolCallDetail): ArtifactRef[] {
  const artifacts: ArtifactRef[] = [];

  try {
    if (detail.toolName === "webSearch") {
      return artifacts;
    }

    if (detail.toolName === "codeInterpreter") {
      if (!isRecord(detail.result)) return artifacts;
      const data = isRecord(detail.result.data) ? detail.result.data : null;
      if (!data) return artifacts;

      const images = Array.isArray(data.images) ? data.images : [];
      for (let i = 0; i < images.length; i++) {
        const image = images[i];
        if (!isRecord(image)) continue;
        const format = getString(image.format) || "image";
        const url = getString(image.url);
        artifacts.push({
          kind: "image",
          displayName: `Generated ${format.toUpperCase()} image ${i + 1}`,
          sandboxPath: null,
          url,
          description: "Image generated by code interpreter.",
          sourceToolName: detail.toolName,
        });
      }

      const files = Array.isArray(data.files) ? data.files : [];
      for (const file of files) {
        if (!isRecord(file)) continue;
        const name = getString(file.name) || "artifact-file";
        const url = getString(file.url);
        const sandboxPath = name.startsWith("/") ? name : null;
        artifacts.push({
          kind: "file",
          displayName: name,
          sandboxPath,
          url,
          description: "File created by code interpreter.",
          sourceToolName: detail.toolName,
        });
      }

      return artifacts;
    }

    if (detail.toolName === "imageGeneration") {
      if (!isRecord(detail.result)) return artifacts;
      const url = getString(detail.result.url);
      artifacts.push({
        kind: "image",
        displayName: "Generated image",
        sandboxPath: null,
        url,
        description: "Image generated from text prompt.",
        sourceToolName: detail.toolName,
      });
      return artifacts;
    }

    if (detail.toolName.startsWith("weblet_")) {
      if (!isRecord(detail.result)) return artifacts;
      const childExecution = isRecord(detail.result._childExecution)
        ? detail.result._childExecution
        : null;
      if (!childExecution) return artifacts;

      const childToolCallsRaw = Array.isArray(childExecution.toolCalls)
        ? childExecution.toolCalls
        : [];

      const childToolCalls: ToolCallDetail[] = childToolCallsRaw
        .filter(isRecord)
        .map((tc) => ({
          toolName: getString(tc.toolName) || "unknown_tool",
          args: isRecord(tc.args) ? tc.args : {},
          result: tc.result ?? null,
        }));

      for (const childCall of childToolCalls) {
        artifacts.push(...extractFromToolCall(childCall));
      }
    }
  } catch {
    return artifacts;
  }

  return artifacts;
}

export function extractArtifacts(toolCallDetails: ToolCallDetail[]): ArtifactRef[] {
  const artifacts: ArtifactRef[] = [];

  for (const detail of toolCallDetails) {
    artifacts.push(...extractFromToolCall(detail));
  }

  return artifacts;
}

export async function generateHandoff(params: {
  agentName: string;
  role: string;
  nodeId: string;
  rawOutput: string;
  toolCallDetails: ToolCallDetail[];
  hasDownstream: boolean;
}): Promise<NodeHandoff> {
  const artifacts = extractArtifacts(params.toolCallDetails);
  const hasFileArtifacts = artifacts.some((artifact) => artifact.kind === "file");
  const workspaceHint = hasFileArtifacts ? `Files in /home/user/nodes/${params.nodeId}/` : "";
  const fallbackOutcome = params.rawOutput.trim().slice(0, 500) || "Task completed.";

  if (!params.hasDownstream) {
    return {
      agentName: params.agentName,
      role: params.role,
      outcomeSummary: fallbackOutcome,
      reasoningSummary: "",
      artifacts,
      workspaceHint,
    };
  }

  let outcomeSummary = fallbackOutcome;
  let reasoningSummary = "";

  if (params.rawOutput.length > 200) {
    try {
      const extraction = await generateObject({
        model: getLanguageModel("openai/gpt-4o-mini"),
        schema: NodeHandoffSchema,
        system:
          "Extract concise structured handoff context for downstream agents. Keep summaries factual and specific.",
        prompt: params.rawOutput,
      });

      outcomeSummary = extraction.object.outcomeSummary || fallbackOutcome;
      reasoningSummary = extraction.object.reasoningSummary || "";
    } catch {
      outcomeSummary = fallbackOutcome;
      reasoningSummary = "";
    }
  }

  return {
    agentName: params.agentName,
    role: params.role,
    outcomeSummary,
    reasoningSummary,
    artifacts,
    workspaceHint,
  };
}
